// LOCAL
### create Task
curl -X POST \
  'http://localhost:8080/tasks' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Task 20",
    "title": "Task 20",
    "description": "Description for Task 20",
    "dueDate": "2023-12-31T23:59:59.999Z",
    "priority": "Medium",
    "completed": true,
    "createdBy": "609c2315bace712ec96dfb20", 
    "tags": ["tag39", "tag40"]
  }'
  

### get all tasks
GET http://localhost:8080/tasks

### get task by id
GET http://localhost:8080/tasks/6532599eb3fefb7d301f7781


### udate task
curl -X PUT \
  'http://localhost:8080/tasks/6532546382186ced6b305ca3' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Task 19",
    "title": "Task 19",
    "description": "Description for Task 19",
    "dueDate": "2023-12-31T23:59:59.999Z",
    "priority": "High",
    "completed": false,
    "createdBy": "609c2315bace712eb96dfb19", 
    "tags": ["tag37", "tag38"]
  }'

#### delete task by id
DELETE http://localhost:8080/tasks/6532546382186ced6b305ca3


// LOCAL
// create user
###
curl -X POST \
  'http://localhost:8080/users' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Alice Johnson",
    "email": "alice@gmail.com.com",
    "username": "alice123",
    "password": "password123",
    "registrationDate": "2023-10-22T12:00:00.000Z",
    "role": "user",
    "status": "active"
  }'


### get all users
GET http://localhost:8080/users

### get  user by id
GET http://localhost:8080/users/6532567e512e36f921a2bfa4


### update users
curl -X PUT \
  'http://localhost:8080/users/6532529682186ced6b305ca1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Jane Smith",
    "email": "janesmith@gmail.com.com",
    "username": "janesmith123",
    "password": "anotherpassword",
    "registrationDate": "2023-10-21T12:00:00.000Z",
    "role": "user",
    "status": "active"
  }'

### delete  user by id
DELETE http://localhost:8080/users/6532529682186ced6b305ca1


#................................................................................................

### PRODUCTION TASKS
### Create task
curl -X 'POST' \
  'https://cse341-project-gqaa.onrender.com/tasks' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Task 20",
    "title": "Task 20",
    "description": "Description for Task 20",
    "dueDate": "2023-12-31T23:59:59.999Z",
    "priority": "Medium",
    "completed": true,
    "createdBy": "609c2315bace712ec96dfb20", 
    "tags": ["tag39", "tag40"]
  }'
  
### Get all tasks
https://cse341-project-gqaa.onrender.com/tasks


### Get task by id
GET https://cse341-project-gqaa.onrender.com/tasks/652ab8d9dbbe1126a8c1a575


### Update task by id
curl -X 'PUT' \
  'https://cse341-project-gqaa.onrender.com/tasks/652ab8d9dbbe1126a8c1a575' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "Dagwan",
  "title": "Mrs",
  "description": "Testing",
  "dueDate": "2023",
  "priority": "Important",
  "completed": "Yes",
  "createdBy": "Dagwan",
  "tags": "Owner"
}'


### Delete task by id
DELETE https://cse341-project-gqaa.onrender.com/tasks/652ab8d9dbbe1126a8c1a575




### PRODUCTION USERS
### Create user
curl -X 'POST' \
  'https://cse341-project-gqaa.onrender.com/users' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Alice Johnson",
    "email": "alice@gmail.com.com",
    "username": "alice123",
    "password": "password123",
    "registrationDate": "2023-10-22T12:00:00.000Z",
    "role": "user",
    "status": "active"
  }'

### Get all users
https://cse341-project-gqaa.onrender.com/users



### Get user by id
GET https://cse341-project-gqaa.onrender.com/users/652ab9e4dbbe1126a8c1a576


### Update user by id
curl -X 'PUT' \
  'https://cse341-project-gqaa.onrender.com/users/65325a7fb3fefb7d301f7783' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Jane Smith",
    "email": "janesmith@gmail.com.com",
    "username": "janesmith123",
    "password": "anotherpassword",
    "registrationDate": "2023-10-21T12:00:00.000Z",
    "role": "user",
    "status": "active"
  }'

### Delete a user
DELETE https://cse341-project-gqaa.onrender.com/users/652ab9e4dbbe1126a8c1a576